language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: osx
      osx_image: xcode8.1
      latex: false

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
