language: r

sudo: required

warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
 - r-cran-rjava

r_packages:
 - rJava
 - covr

r_github_packages:
 - davidgohel/rvg

after_success:
  - Rscript -e 'covr::codecov()'
