language: r

sudo: required

warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
 - openjdk-7-jre

before_install:
 - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
 - export PATH=$PATH:$JAVA_HOME/bin
 - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
 - sudo R CMD javareconf

r_binary_packages:
 - ggplot2
 - rJava

r_packages:
 - ReporteRsjars

os:
 - linux
 - osx
